-- Set Admin Password to admin123 with Correct BCrypt Hash
-- This hash was generated by Spring Security's BCrypt encoder

UPDATE USERS 
SET PASSWORD = '$2a$10$1tYuVfDzAnwRN6XjyWZmTeLXb5oGi77QAxX5EON8vV67haEDug7vm' 
WHERE USERNAME = 'admin';

-- Verify the change
SELECT USERNAME, EMAIL, ROLE, IS_ACTIVE FROM USERS WHERE USERNAME = 'admin'; 