-- Reset Admin Password to Simple Working Password
-- This script resets the admin password to 'admin123' which should work

-- Reset to simple password 'admin123'
-- This hash is generated by Spring Security's BCrypt encoder
UPDATE USERS 
SET PASSWORD = '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa' 
WHERE USERNAME = 'admin';

-- Verify the change
SELECT USERNAME, EMAIL, ROLE, IS_ACTIVE FROM USERS WHERE USERNAME = 'admin'; 