-- Restore Users Script
-- This script restores Jerry, Mian, Gabriel, and Admin users

-- Create Jerry user
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('Jerry', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa', 'jerry@test.com', 'Lab PI', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create Mian user
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('Mian', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa', 'aureliaaa615@gmail.com', 'Master Student', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create Gabriel user
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('Gabriel', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa', '123456@qq.com', 'Master Student', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create Admin user (if not exists)
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDa', 'admin@agenticomics.com', 'Super Admin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create LAB001
INSERT INTO LABS (LAB_ID, LAB_NAME, LAB_DESCRIPTION, INSTITUTION, DEPARTMENT, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('LAB001', 'Genomics Research Lab', 'Advanced genomics and bioinformatics research', 'University of Science', 'Biology Department', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Create LAB002
INSERT INTO LABS (LAB_ID, LAB_NAME, LAB_DESCRIPTION, INSTITUTION, DEPARTMENT, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES ('LAB002', 'Data Science Lab', 'Machine learning and data analysis research', 'University of Technology', 'Computer Science Department', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Add Jerry as Lab PI of LAB001
INSERT INTO USER_LAB_MEMBERSHIPS (USER_ID, LAB_ID, ROLE_IN_LAB, MEMBER_ID, IS_PRIMARY_LAB, IS_ACTIVE, JOINED_AT, CREATED_AT, UPDATED_AT) 
SELECT 
    (SELECT ID FROM USERS WHERE USERNAME = 'Jerry'),
    (SELECT ID FROM LABS WHERE LAB_ID = 'LAB001'),
    'Lab PI',
    'PI001',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP;

-- Add Mian as member of LAB001
INSERT INTO USER_LAB_MEMBERSHIPS (USER_ID, LAB_ID, ROLE_IN_LAB, MEMBER_ID, IS_PRIMARY_LAB, IS_ACTIVE, JOINED_AT, CREATED_AT, UPDATED_AT) 
SELECT 
    (SELECT ID FROM USERS WHERE USERNAME = 'Mian'),
    (SELECT ID FROM LABS WHERE LAB_ID = 'LAB001'),
    'Master Student',
    'MS001',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP;

-- Create TEAM001
INSERT INTO TEAMS (TEAM_ID, TEAM_NAME, TEAM_DESCRIPTION, LAB_ID, TEAM_LEADER_ID, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
SELECT 
    'TEAM001', 
    'Bioinformatics Team', 
    'Genomic data analysis and bioinformatics', 
    'LAB001', 
    (SELECT ID FROM USERS WHERE USERNAME = 'Jerry'), 
    true, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP;

-- Add Jerry as Team Leader of TEAM001
INSERT INTO USER_TEAM_MEMBERSHIPS (USER_ID, TEAM_ID, ROLE_IN_TEAM, MEMBER_ID, IS_PRIMARY_TEAM, IS_ACTIVE, JOINED_AT, CREATED_AT, UPDATED_AT) 
SELECT 
    (SELECT ID FROM USERS WHERE USERNAME = 'Jerry'),
    (SELECT ID FROM TEAMS WHERE TEAM_ID = 'TEAM001'),
    'Team Leader',
    'TL001',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP;

-- Add Mian as member of TEAM001
INSERT INTO USER_TEAM_MEMBERSHIPS (USER_ID, TEAM_ID, ROLE_IN_TEAM, MEMBER_ID, IS_PRIMARY_TEAM, IS_ACTIVE, JOINED_AT, CREATED_AT, UPDATED_AT) 
SELECT 
    (SELECT ID FROM USERS WHERE USERNAME = 'Mian'),
    (SELECT ID FROM TEAMS WHERE TEAM_ID = 'TEAM001'),
    'Team Member',
    'TM001',
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP;
