package com.agenticomics.auth.service;

import com.agenticomics.auth.dto.LabDto;
import com.agenticomics.auth.dto.UserLabMembershipDto;
import com.agenticomics.auth.entity.Lab;
import com.agenticomics.auth.entity.User;
import com.agenticomics.auth.entity.UserLabMembership;
import com.agenticomics.auth.repository.LabRepository;
import com.agenticomics.auth.repository.UserLabMembershipRepository;
import com.agenticomics.auth.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class LabService {
    
    @Autowired
    private LabRepository labRepository;
    
    @Autowired
    private UserLabMembershipRepository userLabMembershipRepository;
    
    @Autowired
    private UserRepository userRepository;
    
    /**
     * Generates the next available lab ID in the format LAB001, LAB002, etc.
     */
    private String generateNextLabId() {
        List<String> existingLabIds = labRepository.findLabIdsOrderedByNumber();
        
        if (existingLabIds.isEmpty()) {
            return "LAB001";
        }
        
        // Get the highest number from existing lab IDs
        String lastLabId = existingLabIds.get(0);
        String numberPart = lastLabId.substring(3); // Remove "LAB" prefix
        
        try {
            int nextNumber = Integer.parseInt(numberPart) + 1;
            return String.format("LAB%03d", nextNumber);
        } catch (NumberFormatException e) {
            // If parsing fails, start from 1
            return "LAB001";
        }
    }
    
    public Lab createLab(String labId, String labName, String labDescription, String institution, String department) {
        // Check if lab ID already exists
        if (labRepository.existsByLabId(labId)) {
            throw new RuntimeException("Lab ID already exists: " + labId);
        }
        
        // Check if lab name already exists
        if (labRepository.existsByLabName(labName)) {
            throw new RuntimeException("Lab name already exists: " + labName);
        }
        
        Lab lab = new Lab();
        lab.setLabId(labId);
        lab.setLabName(labName);
        lab.setLabDescription(labDescription);
        lab.setInstitution(institution);
        lab.setDepartment(department);
        lab.setIsActive(true);
        
        return labRepository.save(lab);
    }
    
    /**
     * Creates a lab with auto-generated ID and adds the creator as Lab PI
     */
    public Lab createLabWithAutoId(String labName, String labDescription, String institution, String department, Long creatorUserId) {
        // Check if lab name already exists
        if (labRepository.existsByLabName(labName)) {
            throw new RuntimeException("Lab name already exists: " + labName);
        }
        
        String autoGeneratedId = generateNextLabId();
        
        Lab lab = new Lab();
        lab.setLabId(autoGeneratedId);
        lab.setLabName(labName);
        lab.setLabDescription(labDescription);
        lab.setInstitution(institution);
        lab.setDepartment(department);
        lab.setIsActive(true);
        
        Lab savedLab = labRepository.save(lab);
        
        // Automatically add the creator as Lab PI
        try {
            addUserToLab(creatorUserId, savedLab.getId(), "Lab PI", "PI001", null, true);
        } catch (Exception e) {
            // If adding user fails, we should still return the created lab
            // Log the error but don't fail the lab creation
            System.err.println("Warning: Failed to add creator to lab: " + e.getMessage());
        }
        
        return savedLab;
    }
    
    /**
     * Gets the next available lab ID without creating the lab
     */
    public String getNextLabId() {
        return generateNextLabId();
    }
    
    public UserLabMembership addUserToLab(Long userId, Long labId, String roleInLab, String memberId, Long supervisorId, Boolean isPrimaryLab) {
        // Check if user is already in this lab
        Optional<UserLabMembership> existingMembership = userLabMembershipRepository
                .findByUserIdAndLabIdAndIsActiveTrue(userId, labId);
        if (existingMembership.isPresent()) {
            throw new RuntimeException("User is already a member of this lab");
        }
        
        // Get user
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found with ID: " + userId));
        
        // Get lab
        Lab lab = labRepository.findById(labId)
                .orElseThrow(() -> new RuntimeException("Lab not found with ID: " + labId));
        
        // Get supervisor if provided
        User supervisor = null;
        if (supervisorId != null) {
            supervisor = userRepository.findById(supervisorId)
                    .orElseThrow(() -> new RuntimeException("Supervisor not found with ID: " + supervisorId));
        }
        
        UserLabMembership membership = new UserLabMembership();
        membership.setUser(user);
        membership.setLab(lab);
        membership.setRoleInLab(roleInLab);
        membership.setMemberId(memberId);
        membership.setSupervisor(supervisor);
        membership.setIsPrimaryLab(isPrimaryLab != null ? isPrimaryLab : false);
        membership.setIsActive(true);
        membership.setJoinedAt(LocalDateTime.now());
        
        return userLabMembershipRepository.save(membership);
    }
    
    public List<LabDto> getAllLabs() {
        return labRepository.findByIsActiveTrue().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public List<UserLabMembershipDto> getUserLabMemberships(String username) {
        Optional<User> userOpt = userRepository.findByUsername(username);
        if (userOpt.isEmpty()) {
            throw new RuntimeException("User not found: " + username);
        }
        
        return userLabMembershipRepository.findActiveMembershipsByUserId(userOpt.get().getId()).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public UserLabMembershipDto getPrimaryLabMembership(String username) {
        Optional<User> userOpt = userRepository.findByUsername(username);
        if (userOpt.isEmpty()) {
            throw new RuntimeException("User not found: " + username);
        }
        
        Optional<UserLabMembership> membership = userLabMembershipRepository
                .findPrimaryLabMembershipByUserId(userOpt.get().getId());
        
        return membership.map(this::convertToDto).orElse(null);
    }
    
    public List<UserLabMembershipDto> getLabMembers(Long labId) {
        return userLabMembershipRepository.findActiveMembershipsByLabId(labId).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public UserLabMembership updateLabMembership(Long membershipId, String roleInLab, String memberId, Long supervisorId, Boolean isPrimaryLab) {
        UserLabMembership membership = userLabMembershipRepository.findById(membershipId)
                .orElseThrow(() -> new RuntimeException("Lab membership not found with ID: " + membershipId));
        
        if (roleInLab != null) {
            membership.setRoleInLab(roleInLab);
        }
        if (memberId != null) {
            membership.setMemberId(memberId);
        }
        if (supervisorId != null) {
            User supervisor = userRepository.findById(supervisorId)
                    .orElseThrow(() -> new RuntimeException("Supervisor not found with ID: " + supervisorId));
            membership.setSupervisor(supervisor);
        }
        if (isPrimaryLab != null) {
            membership.setIsPrimaryLab(isPrimaryLab);
        }
        
        return userLabMembershipRepository.save(membership);
    }
    
    public void removeUserFromLab(Long userId, Long labId) {
        Optional<UserLabMembership> membership = userLabMembershipRepository
                .findByUserIdAndLabIdAndIsActiveTrue(userId, labId);
        
        if (membership.isPresent()) {
            UserLabMembership membershipToUpdate = membership.get();
            membershipToUpdate.setIsActive(false);
            membershipToUpdate.setLeftAt(LocalDateTime.now());
            userLabMembershipRepository.save(membershipToUpdate);
        }
    }
    
    public List<User> getAvailableSupervisorsInLab(Long labId) {
        return userLabMembershipRepository.findActiveMembershipsByLabId(labId).stream()
                .map(UserLabMembership::getUser)
                .filter(user -> "Lab PI".equals(user.getRole()) || "Professor".equals(user.getRole()))
                .collect(Collectors.toList());
    }
    
    private LabDto convertToDto(Lab lab) {
        return new LabDto(
                lab.getId(),
                lab.getLabId(),
                lab.getLabName(),
                lab.getLabDescription(),
                lab.getInstitution(),
                lab.getDepartment(),
                lab.getIsActive(),
                lab.getCreatedAt(),
                lab.getUpdatedAt()
        );
    }
    
    private UserLabMembershipDto convertToDto(UserLabMembership membership) {
        return new UserLabMembershipDto(
                membership.getId(),
                membership.getUser().getId(),
                membership.getUser().getUsername(),
                membership.getLab().getId(),
                membership.getLab().getLabName(),
                membership.getLab().getLabId(),
                membership.getRoleInLab(),
                membership.getMemberId(),
                membership.getSupervisor() != null ? membership.getSupervisor().getId() : null,
                membership.getSupervisor() != null ? membership.getSupervisor().getUsername() : null,
                membership.getIsPrimaryLab(),
                membership.getJoinedAt(),
                membership.getLeftAt(),
                membership.getIsActive(),
                membership.getCreatedAt(),
                membership.getUpdatedAt()
        );
    }
} 