package com.agenticomics.auth.service;

import com.agenticomics.auth.dto.TeamDto;
import com.agenticomics.auth.dto.UserTeamMembershipDto;
import com.agenticomics.auth.entity.Lab;
import com.agenticomics.auth.entity.Team;
import com.agenticomics.auth.entity.User;
import com.agenticomics.auth.entity.UserTeamMembership;
import com.agenticomics.auth.repository.LabRepository;
import com.agenticomics.auth.repository.TeamRepository;
import com.agenticomics.auth.repository.UserRepository;
import com.agenticomics.auth.repository.UserTeamMembershipRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class TeamService {
    
    @Autowired
    private TeamRepository teamRepository;
    
    @Autowired
    private UserTeamMembershipRepository userTeamMembershipRepository;
    
    @Autowired
    private LabRepository labRepository;
    
    @Autowired
    private UserRepository userRepository;
    
    public Team createTeam(String teamId, String teamName, String teamDescription, Long labId, Long teamLeaderId) {
        // Check if team ID already exists
        if (teamRepository.existsByTeamId(teamId)) {
            throw new RuntimeException("Team ID already exists: " + teamId);
        }
        
        // Check if team name already exists
        if (teamRepository.existsByTeamName(teamName)) {
            throw new RuntimeException("Team name already exists: " + teamName);
        }
        
        // Get lab
        Lab lab = labRepository.findById(labId)
                .orElseThrow(() -> new RuntimeException("Lab not found with ID: " + labId));
        
        // Get team leader
        User teamLeader = userRepository.findById(teamLeaderId)
                .orElseThrow(() -> new RuntimeException("User not found with ID: " + teamLeaderId));
        
        Team team = new Team();
        team.setTeamId(teamId);
        team.setTeamName(teamName);
        team.setTeamDescription(teamDescription);
        team.setLab(lab);
        team.setTeamLeader(teamLeader);
        team.setIsActive(true);
        
        return teamRepository.save(team);
    }
    
    /**
     * Creates a team with auto-generated ID and adds the creator as Team Leader
     */
    public Team createTeamWithAutoId(String teamName, String teamDescription, Long labId, Long creatorUserId) {
        // Check if team name already exists
        if (teamRepository.existsByTeamName(teamName)) {
            throw new RuntimeException("Team name already exists: " + teamName);
        }
        
        // Get lab
        Lab lab = labRepository.findById(labId)
                .orElseThrow(() -> new RuntimeException("Lab not found with ID: " + labId));
        
        // Get creator user
        User creator = userRepository.findById(creatorUserId)
                .orElseThrow(() -> new RuntimeException("User not found with ID: " + creatorUserId));
        
        // Generate team ID
        String autoGeneratedId = generateNextTeamId();
        
        Team team = new Team();
        team.setTeamId(autoGeneratedId);
        team.setTeamName(teamName);
        team.setTeamDescription(teamDescription);
        team.setLab(lab);
        team.setTeamLeader(creator);
        team.setIsActive(true);
        
        Team savedTeam = teamRepository.save(team);
        
        // Automatically add the creator as Team Leader
        try {
            addUserToTeam(creatorUserId, savedTeam.getId(), "Team Leader", "TL001", null, true);
        } catch (Exception e) {
            // If adding user fails, we should still return the created team
            // Log the error but don't fail the team creation
            System.err.println("Warning: Failed to add creator to team: " + e.getMessage());
        }
        
        return savedTeam;
    }
    
    public UserTeamMembership addUserToTeam(Long userId, Long teamId, String roleInTeam, String memberId, Long supervisorId, Boolean isPrimaryTeam) {
        // Check if user is already in this team
        Optional<UserTeamMembership> existingMembership = userTeamMembershipRepository
                .findByUserIdAndTeamIdAndIsActiveTrue(userId, teamId);
        if (existingMembership.isPresent()) {
            throw new RuntimeException("User is already a member of this team");
        }
        
        // Get user
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found with ID: " + userId));
        
        // Get team
        Team team = teamRepository.findById(teamId)
                .orElseThrow(() -> new RuntimeException("Team not found with ID: " + teamId));
        
        // Get supervisor if provided
        User supervisor = null;
        if (supervisorId != null) {
            supervisor = userRepository.findById(supervisorId)
                    .orElseThrow(() -> new RuntimeException("Supervisor not found with ID: " + supervisorId));
        }
        
        UserTeamMembership membership = new UserTeamMembership();
        membership.setUser(user);
        membership.setTeam(team);
        membership.setRoleInTeam(roleInTeam);
        membership.setMemberId(memberId);
        membership.setSupervisor(supervisor);
        membership.setIsPrimaryTeam(isPrimaryTeam != null ? isPrimaryTeam : false);
        membership.setIsActive(true);
        membership.setJoinedAt(LocalDateTime.now());
        
        return userTeamMembershipRepository.save(membership);
    }
    
    public List<TeamDto> getAllTeams() {
        return teamRepository.findByIsActiveTrue().stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public List<TeamDto> getTeamsByLabId(Long labId) {
        return teamRepository.findActiveTeamsByLabId(labId).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public List<UserTeamMembershipDto> getUserTeamMemberships(String username) {
        Optional<User> userOpt = userRepository.findByUsername(username);
        if (userOpt.isEmpty()) {
            throw new RuntimeException("User not found: " + username);
        }
        
        return userTeamMembershipRepository.findActiveMembershipsByUserId(userOpt.get().getId()).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public UserTeamMembershipDto getPrimaryTeamMembership(String username) {
        Optional<User> userOpt = userRepository.findByUsername(username);
        if (userOpt.isEmpty()) {
            throw new RuntimeException("User not found: " + username);
        }
        
        Optional<UserTeamMembership> membership = userTeamMembershipRepository
                .findPrimaryTeamMembershipByUserId(userOpt.get().getId());
        
        return membership.map(this::convertToDto).orElse(null);
    }
    
    public List<UserTeamMembershipDto> getTeamMembers(Long teamId) {
        return userTeamMembershipRepository.findActiveMembershipsByTeamId(teamId).stream()
                .map(this::convertToDto)
                .collect(Collectors.toList());
    }
    
    public UserTeamMembership updateTeamMembership(Long membershipId, String roleInTeam, String memberId, Long supervisorId, Boolean isPrimaryTeam) {
        UserTeamMembership membership = userTeamMembershipRepository.findById(membershipId)
                .orElseThrow(() -> new RuntimeException("Team membership not found with ID: " + membershipId));
        
        if (roleInTeam != null) {
            membership.setRoleInTeam(roleInTeam);
        }
        if (memberId != null) {
            membership.setMemberId(memberId);
        }
        if (supervisorId != null) {
            User supervisor = userRepository.findById(supervisorId)
                    .orElseThrow(() -> new RuntimeException("Supervisor not found with ID: " + supervisorId));
            membership.setSupervisor(supervisor);
        }
        if (isPrimaryTeam != null) {
            membership.setIsPrimaryTeam(isPrimaryTeam);
        }
        
        return userTeamMembershipRepository.save(membership);
    }
    
    public void removeUserFromTeam(Long userId, Long teamId) {
        Optional<UserTeamMembership> membership = userTeamMembershipRepository
                .findByUserIdAndTeamIdAndIsActiveTrue(userId, teamId);
        
        if (membership.isPresent()) {
            UserTeamMembership membershipToUpdate = membership.get();
            membershipToUpdate.setIsActive(false);
            membershipToUpdate.setLeftAt(LocalDateTime.now());
            userTeamMembershipRepository.save(membershipToUpdate);
        }
    }
    
    /**
     * Generates the next available team ID in the format TEAM001, TEAM002, etc.
     */
    private String generateNextTeamId() {
        List<String> existingTeamIds = teamRepository.findTeamIdsOrderedByNumber();
        
        if (existingTeamIds.isEmpty()) {
            return "TEAM001";
        }
        
        // Get the highest number from existing team IDs
        String lastTeamId = existingTeamIds.get(0);
        String numberPart = lastTeamId.substring(4); // Remove "TEAM" prefix
        
        try {
            int nextNumber = Integer.parseInt(numberPart) + 1;
            return String.format("TEAM%03d", nextNumber);
        } catch (NumberFormatException e) {
            // If parsing fails, start from 1
            return "TEAM001";
        }
    }
    
    /**
     * Public method to get the next team ID
     */
    public String getNextTeamId() {
        return generateNextTeamId();
    }
    
    public boolean isUserMemberOfTeam(Long userId, Long teamId) {
        Optional<UserTeamMembership> membership = userTeamMembershipRepository
                .findByUserIdAndTeamIdAndIsActiveTrue(userId, teamId);
        return membership.isPresent();
    }
    
    private TeamDto convertToDto(Team team) {
        return new TeamDto(
                team.getId(),
                team.getTeamId(),
                team.getTeamName(),
                team.getTeamDescription(),
                team.getLab() != null ? team.getLab().getId() : null,
                team.getLab() != null ? team.getLab().getLabName() : null,
                team.getTeamLeader() != null ? team.getTeamLeader().getId() : null,
                team.getTeamLeader() != null ? team.getTeamLeader().getUsername() : null,
                team.getIsActive(),
                team.getCreatedAt(),
                team.getUpdatedAt()
        );
    }
    
    private UserTeamMembershipDto convertToDto(UserTeamMembership membership) {
        return new UserTeamMembershipDto(
                membership.getId(),
                membership.getUser().getId(),
                membership.getUser().getUsername(),
                membership.getTeam().getId(),
                membership.getTeam().getTeamName(),
                membership.getTeam().getTeamId(),
                membership.getRoleInTeam(),
                membership.getMemberId(),
                membership.getSupervisor() != null ? membership.getSupervisor().getId() : null,
                membership.getSupervisor() != null ? membership.getSupervisor().getUsername() : null,
                membership.getIsPrimaryTeam(),
                membership.getJoinedAt(),
                membership.getLeftAt(),
                membership.getIsActive(),
                membership.getCreatedAt(),
                membership.getUpdatedAt()
        );
    }
} 